import 'package:citivoice_admin/Core/constant/image_constant.dart';

final List<Map<String, String>> citizensList = [
  {
    'image': ImageConstant.person,
    'first_name': 'محمد',
    'father': 'ملهم',
    'last_name': 'الزقيمي',
    'mobiel': '0935650123',
    'email': 'm.zakimi@gmail.com',
    'idnumber': '011234567',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'أحمد',
    'father': 'خالد',
    'last_name': 'الأحمد',
    'mobiel': '0944455666',
    'email': 'ahmad.khaled@gmail.com',
    'idnumber': '012345678',
    'status': 'موقوف',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'سارة',
    'father': 'محمود',
    'last_name': 'حسن',
    'mobiel': '0959988776',
    'email': 'sara.mahmoud@gmail.com',
    'idnumber': '019876543',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'محمد',
    'father': 'ملهم',
    'last_name': 'الزقيمي',
    'mobiel': '0935650123',
    'email': 'm.zakimi@gmail.com',
    'idnumber': '011234567',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'أحمد',
    'father': 'خالد',
    'last_name': 'الأحمد',
    'mobiel': '0944455666',
    'email': 'ahmad.khaled@gmail.com',
    'idnumber': '012345678',
    'status': 'موقوف',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'سارة',
    'father': 'محمود',
    'last_name': 'حسن',
    'mobiel': '0959988776',
    'email': 'sara.mahmoud@gmail.com',
    'idnumber': '019876543',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'محمد',
    'father': 'ملهم',
    'last_name': 'الزقيمي',
    'mobiel': '0935650123',
    'email': 'm.zakimi@gmail.com',
    'idnumber': '011234567',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'أحمد',
    'father': 'خالد',
    'last_name': 'الأحمد',
    'mobiel': '0944455666',
    'email': 'ahmad.khaled@gmail.com',
    'idnumber': '012345678',
    'status': 'موقوف',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'سارة',
    'father': 'محمود',
    'last_name': 'حسن',
    'mobiel': '0959988776',
    'email': 'sara.mahmoud@gmail.com',
    'idnumber': '019876543',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'محمد',
    'father': 'ملهم',
    'last_name': 'الزقيمي',
    'mobiel': '0935650123',
    'email': 'm.zakimi@gmail.com',
    'idnumber': '011234567',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'أحمد',
    'father': 'خالد',
    'last_name': 'الأحمد',
    'mobiel': '0944455666',
    'email': 'ahmad.khaled@gmail.com',
    'idnumber': '012345678',
    'status': 'موقوف',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'سارة',
    'father': 'محمود',
    'last_name': 'حسن',
    'mobiel': '0959988776',
    'email': 'sara.mahmoud@gmail.com',
    'idnumber': '019876543',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'محمد',
    'father': 'ملهم',
    'last_name': 'الزقيمي',
    'mobiel': '0935650123',
    'email': 'm.zakimi@gmail.com',
    'idnumber': '011234567',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'أحمد',
    'father': 'خالد',
    'last_name': 'الأحمد',
    'mobiel': '0944455666',
    'email': 'ahmad.khaled@gmail.com',
    'idnumber': '012345678',
    'status': 'موقوف',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'سارة',
    'father': 'محمود',
    'last_name': 'حسن',
    'mobiel': '0959988776',
    'email': 'sara.mahmoud@gmail.com',
    'idnumber': '019876543',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'محمد',
    'father': 'ملهم',
    'last_name': 'الزقيمي',
    'mobiel': '0935650123',
    'email': 'm.zakimi@gmail.com',
    'idnumber': '011234567',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'أحمد',
    'father': 'خالد',
    'last_name': 'الأحمد',
    'mobiel': '0944455666',
    'email': 'ahmad.khaled@gmail.com',
    'idnumber': '012345678',
    'status': 'موقوف',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'سارة',
    'father': 'محمود',
    'last_name': 'حسن',
    'mobiel': '0959988776',
    'email': 'sara.mahmoud@gmail.com',
    'idnumber': '019876543',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'محمد',
    'father': 'ملهم',
    'last_name': 'الزقيمي',
    'mobiel': '0935650123',
    'email': 'm.zakimi@gmail.com',
    'idnumber': '011234567',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'أحمد',
    'father': 'خالد',
    'last_name': 'الأحمد',
    'mobiel': '0944455666',
    'email': 'ahmad.khaled@gmail.com',
    'idnumber': '012345678',
    'status': 'موقوف',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'سارة',
    'father': 'محمود',
    'last_name': 'حسن',
    'mobiel': '0959988776',
    'email': 'sara.mahmoud@gmail.com',
    'idnumber': '019876543',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'محمد',
    'father': 'ملهم',
    'last_name': 'الزقيمي',
    'mobiel': '0935650123',
    'email': 'm.zakimi@gmail.com',
    'idnumber': '011234567',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'أحمد',
    'father': 'خالد',
    'last_name': 'الأحمد',
    'mobiel': '0944455666',
    'email': 'ahmad.khaled@gmail.com',
    'idnumber': '012345678',
    'status': 'موقوف',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'سارة',
    'father': 'محمود',
    'last_name': 'حسن',
    'mobiel': '0959988776',
    'email': 'sara.mahmoud@gmail.com',
    'idnumber': '019876543',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'محمد',
    'father': 'ملهم',
    'last_name': 'الزقيمي',
    'mobiel': '0935650123',
    'email': 'm.zakimi@gmail.com',
    'idnumber': '011234567',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'أحمد',
    'father': 'خالد',
    'last_name': 'الأحمد',
    'mobiel': '0944455666',
    'email': 'ahmad.khaled@gmail.com',
    'idnumber': '012345678',
    'status': 'موقوف',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'سارة',
    'father': 'محمود',
    'last_name': 'حسن',
    'mobiel': '0959988776',
    'email': 'sara.mahmoud@gmail.com',
    'idnumber': '019876543',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'محمد',
    'father': 'ملهم',
    'last_name': 'الزقيمي',
    'mobiel': '0935650123',
    'email': 'm.zakimi@gmail.com',
    'idnumber': '011234567',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'أحمد',
    'father': 'خالد',
    'last_name': 'الأحمد',
    'mobiel': '0944455666',
    'email': 'ahmad.khaled@gmail.com',
    'idnumber': '012345678',
    'status': 'موقوف',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'سارة',
    'father': 'محمود',
    'last_name': 'حسن',
    'mobiel': '0959988776',
    'email': 'sara.mahmoud@gmail.com',
    'idnumber': '019876543',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'محمد',
    'father': 'ملهم',
    'last_name': 'الزقيمي',
    'mobiel': '0935650123',
    'email': 'm.zakimi@gmail.com',
    'idnumber': '011234567',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'أحمد',
    'father': 'خالد',
    'last_name': 'الأحمد',
    'mobiel': '0944455666',
    'email': 'ahmad.khaled@gmail.com',
    'idnumber': '012345678',
    'status': 'موقوف',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'سارة',
    'father': 'محمود',
    'last_name': 'حسن',
    'mobiel': '0959988776',
    'email': 'sara.mahmoud@gmail.com',
    'idnumber': '019876543',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'محمد',
    'father': 'ملهم',
    'last_name': 'الزقيمي',
    'mobiel': '0935650123',
    'email': 'm.zakimi@gmail.com',
    'idnumber': '011234567',
    'status': 'فعال',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'أحمد',
    'father': 'خالد',
    'last_name': 'الأحمد',
    'mobiel': '0944455666',
    'email': 'ahmad.khaled@gmail.com',
    'idnumber': '012345678',
    'status': 'موقوف',
  },
  {
    'image': ImageConstant.person,
    'first_name': 'سارة',
    'father': 'محمود',
    'last_name': 'حسن',
    'mobiel': '0959988776',
    'email': 'sara.mahmoud@gmail.com',
    'idnumber': '019876543',
    'status': 'فعال',
  },
];
